version: "4.22.1"

services:
  database:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: student_survey_db
    restart: always
  web:   
    build: ./ResourceManager
    environment:
      MYSQL_DATABASE: student_survey_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: on-failure